apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  selector:
    matchLabels:
      app:  fleetman-position-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app:  fleetman-position-simulator
    spec:
      containers:
      - name:  fleetman-position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
